### ISSUE TITLE
[vaadin challenge] issue on liberty server.xml 

### ISSUE THREAD

**Issue by bedinsky** [mstahv/watson-java-api#2]
I've tried to deploy example app using cloud foundry with a liberty server but it seems there are some incompatible libraries.
Is it possible to deploy example war in a different way on cloud foundry

I got this error 

[ERROR ] CWWKF0033E: The singleton features com.ibm.websphere.appserver.javaeeCompatible-6.0 and com.ibm.websphere.appserver.javaeeCompatible-7.0 cannot be loaded at the same time. The configured features jsf-2.0 and jaxrs-2.0 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.

it seem that is cdi-1.0 available on Java™ EE 6 Web Profile and  jaxrs-2.0 available on Java™ EE 7 Web Profile

I've tried to use cdi-1.2 

and the webapp was started
[AUDIT ] CWWKF0012I: The server installed the following features: [jsf-2.0, jsp-2.2, managedBeans-1.0, ejbLite-3.2, servlet-3.1, beanValidation-1.1, jndi-1.0, localConnector-1.0, icap:managementConnector-1.0, jaxrs-2.0, jaxrsClient-2.0, el-3.0, json-1.0, cdi-1.2, appState-1.0].

but I've got a different error

2015-11-21T20:45:19.319+0100[App/0]ERR[ERROR ] SRVE0283E: Exception caught while initializing context: java.lang.NoClassDefFoundError: javax.enterprise.util.AnnotationLiteral
2015-11-21T20:45:19.319+0100[App/0]ERR at com.vaadin.cdi.internal.ContextDeployer.contextInitialized(ContextDeployer.java:63)

Regards

**Comment by mstahv** [comment]
Hi,

Do you have the latest Liberty? You will need jaxrs-2.0/jaxrsClient-2.0, but you don't need jsf at all as you are using Vaadin for UI. You could also try so that you just configure the full java ee 7 feature set for your liberty, that should contain all needed stuff. I hope this helps,

**Comment by bedinsky** [comment]
Hi,
thank you for answering, I have  liberty-2015.10.0_0, ibmjdk-1.8.0_20150828
Probably it needs to remove jsf but I gave up with liberty war and I tried to deploy war created with normal maven build. 
App was deployed but viritin cdn widgset cannot be loaded.
So I used standard widgeset and app started / watson image recognition service worked.
However I'm not able to run it a locally copying vcap_services in a deltaspike property file .
I tried mvn wildfly:run but bluemix service throws an exception at init. 
Also calling directly a bluemix rest service with a rest client  does not work.
It seems that I can call services only from liberty server running on bluemix

**Comment by mstahv** [comment]
I haven't tried the project lately. Maybe they have closed the service from external addresses? What was the thrown exception, does it give any hints?

**Comment by bedinsky** [comment]
No hints from exception, I'm a complete noob with wildfly and delta-spike !!!
This is not blocking my vaadin bluemix challenge but it will take more time if I cannot test application locally

**this is runtime exception after clicking on upload buttom**

at java.lang.Thread.run(Thread.java:745)
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method uploadSucceeded in org.example.VisualRecognitionView$2 failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1003)
    at com.vaadin.ui.Upload.fireUploadSuccess(Upload.java:888)
    at com.vaadin.ui.Upload$2.streamingFinished(Upload.java:1150)
    at com.vaadin.server.communication.FileUploadHandler.streamToReceiver(FileUploadHandler.java:597)
    ... 34 more
Caused by: org.jboss.weld.exceptions.WeldException: WELD-000049: Unable to invoke public void org.watson.BluemixServices.init() on org.watson.BluemixServices@45cb12c4
    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:100)
    at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:81)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:126)

**apache-deltaspike.properties has been found on app start up**

10:20:32,334 INFO  [org.apache.deltaspike.core.impl.config.EnvironmentPropertyConfigSourceProvider](MSC service thread 1-4) Custom config found by DeltaSpike. Name: 'META-INF/apache-deltaspike.properties', URL: 'vfs:/content/watson-java-example-1.0-SNAPSHOT.war/WEB-INF/classes/META-INF/apache-deltaspike.properties'

**deltaspike related warning on app start up**
10:20:34,136 WARN  [org.jboss.weld.Bootstrap](weld-worker-4) WELD-001125: Illegal bean type java.util.Comparator<org.apache.deltaspike.core.api.exception.control.HandlerMethod<?>> ignored on [EnhancedAnnotatedTypeImpl] public final  class org.apache.deltaspike.core.impl.exception.control.ExceptionHandlerComparator
